# -*- coding: utf-8 -*-
"""Atividade de aplicação 1: Zodíaco Jurássico

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DcGCRH8bEVmBuYEyN6nOhVnFnXBnD717
"""

#Sophia Victória Borguezan Kim 11202320185

mes = int(input())
if mes == 1:
  print("Voce nasceu em janeiro, portanto seu signo e mosassauro")
elif mes == 2:
  print("Voce nasceu em fevereiro, portanto seu signo e pteranodonte")
elif mes == 3:
  print("Voce nasceu em marco, portanto seu signo e anquilossauro")
elif mes == 4:
  print("Voce nasceu em abril, portanto seu signo e hypsilophodon")
elif mes == 5:
  print("Voce nasceu em maio, portanto seu signo e braquiossauro")
elif mes == 6:
  print("Voce nasceu em junho, portanto seu signo e fukuiraptor")
elif mes == 7:
  print("Voce nasceu em julho, portanto seu signo e giraffatitan")
elif mes == 8:
  print("Voce nasceu em agosto, portanto seu signo e triceratops")
elif mes == 9:
  print("Voce nasceu em setembro, portanto seu signo e iguanodon")
elif mes == 10:
  print("Voce nasceu em outubro, portanto seu signo e bagaceratops")
elif mes == 11:
  print("Voce nasceu em novembro, portanto seu signo e velociraptor")
elif mes == 12:
  print("Voce nasceu em dezembro, portanto seu signo e parasaurolophus")
else:
  print("inválido")