# -*- coding: utf-8 -*-
"""Atividade de fixação 7 - Repetições

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtdYnnclTtUE-keGkG1FmnggeJKme2ki
"""

#Sophia Victória Borguezan Kim 11202320185

n = int(input())

somatorio = 0
for _ in range(n):
    num = int(input())

    if num % 2 == 0:
        somatorio += 2 * num
    else:
        somatorio += 3 * num

print(somatorio)