# -*- coding: utf-8 -*-
"""Atividade de fixação 4 - Quartis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iv7tISrxzL1MHsNm0ANka2NHRzJis2FA
"""

#Sophia Victória Borguezan Kim 11202320185

import pandas as pd
import numpy as np

df = pd.read_csv(input())

q1 = np.percentile(df["nota"], q=25)
q2 = np.percentile(df["nota"], q=50)
q3 = np.percentile(df["nota"], q=75)

print("%.2f" % q1)
print("%.2f" % q2)
print("%.2f" % q3)