# -*- coding: utf-8 -*-
"""Atividade de aplicação 6 - Nota fiscal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14S2S-ouALMOZwnN40QdQgvlL5UqcGWgP
"""

#Sophia Victória Borguezan Kim 11202320185

n = int(input())

total = 0.0
for _ in range(n):
    quantidade = int(input())
    preco = float(input())
    promocao = input().lower() == "sim"

    custo = quantidade * preco

    if promocao:
        if quantidade >= 5 and quantidade <= 9:
            desconto = 0.10
        elif quantidade >= 10:
            desconto = 0.15
        else:
            desconto = 0.0
        custo -= custo * desconto

    total += custo

print("Total:", "%.2f" % total)

if total > 1000:
    print("A compra pode ser parcelada")