# -*- coding: utf-8 -*-
"""Atividade de fixação 2 - Seno

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGllRe7USGeYUcFuzIImnEitUEirNe2p
"""

#Sophia Victória Borguezan Kim 11202320185

import numpy as np

N = float(input())

arange = np.arange (1, N, 0.5)
x = np.sin(arange)
print(x)