# -*- coding: utf-8 -*-
"""Atividade de aplicação 2: Funções Trigonométricas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wM8qv2znlWlR_-I_J8tNXJDtV9njtito
"""

# Commented out IPython magic to ensure Python compatibility.
#Sophia Victória Borguezan Kim 11202320185

import numpy as np
import matplotlib
# %matplotlib inline

inicio = float(input())
fim = float(input())
incremento = float(input())
x = input()

arange = np.arange (inicio, fim, incremento)
print(arange)

if x == "seno":
  x = np.arange(inicio, fim, incremento)
  y = np.sin(arange)
  soma = sum(y)

elif x == "cosseno":
  x = np.arange(inicio, fim, incremento)
  y = np.cos(arange)
  soma = sum(y)

elif x == "log10":
  x = np.arange(inicio, fim, incremento)
  y = np.log10(arange)
  soma = sum(y)

elif x == "raiz2":
  x = np.arange(inicio, fim, incremento)
  y = np.sqrt(arange)
  soma = sum(y)

elif x == "pot2":
  x = np.arange(inicio, fim, incremento)
  y = arange**2
  soma = sum(y)

else:
  print(input("invalido"))
print(y)

print("%.2f" % soma)