# -*- coding: utf-8 -*-
"""Atividade de fixação 6 - Senha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_hJNHS9vmsib9Rlvq3fFkHgBoyONHEt
"""

#Sophia Victória Borguezan Kim 11202320185

senhas = {
    1: "mico-leao-dourado",
    2: "boto-cor-de-rosa",
    3: "arara-azul",
    4: "onca-pintada",
    5: "sucuri",
    6: "capivara"
}

while True:
    try:
        n = int(input())
        if 1 <= n <= 6:
            break
        print("Numero invalido. Digite um numero entre 1 e 6.")
    except ValueError:
        print("Entrada invalida. Digite um numero inteiro.")

while input("") != senhas[n]:
    print("Senha invalida")

print("Senha correta")