# -*- coding: utf-8 -*-
"""Atividade de aplicação 0 - IMC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QbO1UE-xoaERhmdPaf4eMrgthK92c1Bn
"""

#Sophia Victória Borguezan Kim 11202320185

altura = float(input())
peso = float(input())
imc = peso /(altura**2)
print("%.2f" % imc)