# -*- coding: utf-8 -*-
"""Atividade de aplicação 5 - Velocidade

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NebE5pzfNwqGSpYtGxWHtBdTQj3T_9Vf
"""

#Sophia Victória Borguezan Kim 11202320185

v0 = float(input())
s0 = float(input())
a = float(input())
t = int(input())

for t in range(1, t+1):
    v = 0
    s = 0
    v = v0 + (a * t)
    s = s0 + (v0 * t) + (a * t**2 / 2)
    print("Tempo:", +t, "segundo(s)")
    print("Posicao:", "%.2f" % +s, "metro(s)")
    print("Velocidade:", "%.2f" % +v, "m/s")
    print("===")