# -*- coding: utf-8 -*-
"""Atividade de fixação 5 - Correlação e Regressão

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtXMkGY1YRdSnrb_3MNZgntQ5qJmAtOw
"""

#Sophia Victória Borguezan Kim 11202320185
import pandas as pd

arquivo = input()

df = pd.read_csv(arquivo)
corr = df['Pressao Atmosferica {kPa}'].corr(df['T. Pto Orvalho {C}'])
a = df[['Pressao Atmosferica {kPa}', 'T. Pto Orvalho {C}']].cov().iloc[0, 1] / df['Pressao Atmosferica {kPa}'].var()
b = df['T. Pto Orvalho {C}'].mean() - a * df['Pressao Atmosferica {kPa}'].mean()

print(f"{corr:.4f}")
print(f"{a:.4f}")
print(f"{b:.4f}")