# -*- coding: utf-8 -*-
"""Atividade de aplicação 4 - Notas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12M99S_ZFz_m78v3gn_Cfk8RHsoxcfKVg
"""

#Sophia Victória Borguezan Kim 11202320185

import pandas as pd
import numpy as np

df = pd.read_csv("notas.csv")

m = input()
n = input()

corr = df[("nota_tarefa"+m)].corr(df[("nota_tarefa"+n)])
print("Correlacao: %.2f" % corr)

if corr >= 0.9 or corr <= -0.9:
  print("Correlacao muito forte")

elif (corr >= 0.7 and corr < 0.9) or (corr <= -0.7 and corr > -0.9):
  print("Correlacao forte")
 
else:
  print("Correlacao meh")

x = df["nota_tarefa"+m]
y = df["nota_tarefa"+n]

(a, b) = np.polyfit(x=df["nota_tarefa"+m], y=df["nota_tarefa"+n], deg = 1)
print("%.2f" % a)
print("%.2f" % b)