# -*- coding: utf-8 -*-
"""Atividade de fixação 1 - Soma

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16msYxZmxphj70drIAsH8Cd6mDpjcp4Id
"""

#Sophia Victória Borguezan Kim 11202320185

n1 = int(input())
n2 = int(input())

print(n1 + n2)